# _config.yml
title: Ajdmatrix
author: Kagami
description: >-
  Ajdmatrix website

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  math_engine: katex

# theme: jekyll-theme-minimal

collections:
  chapters:
    output: true
    permalink: /:collection/:name
